// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Space_Race.DAL;

#nullable disable

namespace Space_Race.DAL.Migrations
{
    [DbContext(typeof(SpRaceDbContext))]
    partial class SpRaceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Space_Race.Models.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("DriverId");

                    b.HasIndex("TournamentId");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("Space_Race.Models.Tournament", b =>
                {
                    b.Property<int>("TournamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TournamentId"));

                    b.Property<string>("RaceWinners")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TourFirstPlaceDriverId")
                        .HasColumnType("int");

                    b.Property<int?>("TourFirstPlaceId")
                        .HasColumnType("int");

                    b.Property<int?>("TourSecondPlaceDriverId")
                        .HasColumnType("int");

                    b.Property<int?>("TourSecondPlaceId")
                        .HasColumnType("int");

                    b.Property<int?>("TourThirdPlaceDriverId")
                        .HasColumnType("int");

                    b.Property<int?>("TourThirdPlaceId")
                        .HasColumnType("int");

                    b.HasKey("TournamentId");

                    b.HasIndex("TourFirstPlaceDriverId");

                    b.HasIndex("TourSecondPlaceDriverId");

                    b.HasIndex("TourThirdPlaceDriverId");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("Space_Race.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VehicleId");

                    b.HasIndex("DriverId")
                        .IsUnique()
                        .HasFilter("[DriverId] IS NOT NULL");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Space_Race.Models.Driver", b =>
                {
                    b.HasOne("Space_Race.Models.Tournament", null)
                        .WithMany("Drivers")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Space_Race.Models.Tournament", b =>
                {
                    b.HasOne("Space_Race.Models.Driver", "TourFirstPlace")
                        .WithMany()
                        .HasForeignKey("TourFirstPlaceDriverId");

                    b.HasOne("Space_Race.Models.Driver", "TourSecondPlace")
                        .WithMany()
                        .HasForeignKey("TourSecondPlaceDriverId");

                    b.HasOne("Space_Race.Models.Driver", "TourThirdPlace")
                        .WithMany()
                        .HasForeignKey("TourThirdPlaceDriverId");

                    b.Navigation("TourFirstPlace");

                    b.Navigation("TourSecondPlace");

                    b.Navigation("TourThirdPlace");
                });

            modelBuilder.Entity("Space_Race.Models.Vehicle", b =>
                {
                    b.HasOne("Space_Race.Models.Driver", "Driver")
                        .WithOne("Vehicle")
                        .HasForeignKey("Space_Race.Models.Vehicle", "DriverId");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Space_Race.Models.Driver", b =>
                {
                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Space_Race.Models.Tournament", b =>
                {
                    b.Navigation("Drivers");
                });
#pragma warning restore 612, 618
        }
    }
}
